#!/bin/bash

set -e

echo "Build hook running."

SDK_VERSION="${SDK_VERSION:-1.37.37}"
CPU_CORES="${CPU_CORES:-4}"

echo "Building fastcomp (LLVM & CLANG)"
docker build --build-arg FROM_IMAGE="${FROM_IMAGE}" \
--build-arg SDK_VERSION="${SDK_VERSION}" \
--build-arg CPU_CORES="${CPU_CORES}" \
-t "${IMAGE_NAME}" .

