#!/bin/bash

set -e

echo "Build hook running."

CPU_CORES="${CPU_CORES:-4}"
Z3_VERSION="${Z3_VERSION:-z3-4.6.0}"

echo "Building Z3"
docker build --build-arg FROM_IMAGE="${FROM_IMAGE}" \
--build-arg Z3_VERSION="${Z3_VERSION}" \
--build-arg CPU_CORES="${CPU_CORES}" \
-t "${IMAGE_NAME}" .
